-- PlumeNote — Seed Data
-- 4 domains, 11 document types, 10 templates, 1 admin, default config

BEGIN;

-- 4 Domains
INSERT INTO domains (id, name, slug, color, icon, sort_order) VALUES
    ('d0000000-0000-0000-0000-000000000001', 'SCI', 'sci', '#3B82F6', 'monitor', 1),
    ('d0000000-0000-0000-0000-000000000002', 'Etudes & Dev', 'etudes-dev', '#10B981', 'code', 2),
    ('d0000000-0000-0000-0000-000000000003', 'Infrastructure', 'infrastructure', '#F59E0B', 'server', 3),
    ('d0000000-0000-0000-0000-000000000004', 'Support', 'support', '#EF4444', 'headphones', 4)
ON CONFLICT (id) DO NOTHING;

-- 11 Document Types (10 + "Autre")
INSERT INTO document_types (id, name, slug, icon, sort_order) VALUES
    ('t0000000-0000-0000-0000-000000000001', 'Procedure technique', 'procedure-technique', 'list-checks', 1),
    ('t0000000-0000-0000-0000-000000000002', 'Guide utilisateur', 'guide-utilisateur', 'book-open', 2),
    ('t0000000-0000-0000-0000-000000000003', 'Architecture systeme', 'architecture-systeme', 'network', 3),
    ('t0000000-0000-0000-0000-000000000004', 'FAQ', 'faq', 'help-circle', 4),
    ('t0000000-0000-0000-0000-000000000005', 'Troubleshooting', 'troubleshooting', 'bug', 5),
    ('t0000000-0000-0000-0000-000000000006', 'Fiche applicative', 'fiche-applicative', 'layout', 6),
    ('t0000000-0000-0000-0000-000000000007', 'Procedure d''installation', 'procedure-installation', 'download', 7),
    ('t0000000-0000-0000-0000-000000000008', 'Note de version', 'note-de-version', 'git-branch', 8),
    ('t0000000-0000-0000-0000-000000000009', 'Guide reseau', 'guide-reseau', 'wifi', 9),
    ('t0000000-0000-0000-0000-000000000010', 'Documentation API', 'documentation-api', 'terminal', 10),
    ('t0000000-0000-0000-0000-000000000011', 'Autre', 'autre', 'file', 11)
ON CONFLICT (id) DO NOTHING;

-- 10 Templates with TipTap JSON content
INSERT INTO templates (id, name, description, content, type_id, is_default, usage_count) VALUES
-- T-01: Procedure Technique
('e0000000-0000-0000-0000-000000000001', 'Procedure technique', 'Pour toute operation a realiser etape par etape',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"[Titre de la procedure]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Objectif"}]},{"type":"paragraph","content":[{"type":"text","text":"[Decrivez en 1-2 phrases ce que cette procedure permet d''accomplir]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Prerequis"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Acces requis]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Outils necessaires]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Conditions prealables]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Etapes"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"1. [Premiere etape]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Description detaillee]"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"2. [Deuxieme etape]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Description detaillee]"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"3. [Troisieme etape]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Description detaillee]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Verification"}]},{"type":"paragraph","content":[{"type":"text","text":"[Comment verifier que la procedure a ete executee correctement]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"En cas de probleme"}]},{"type":"paragraph","content":[{"type":"text","text":"[Que faire si ca ne fonctionne pas]"}]}]}',
't0000000-0000-0000-0000-000000000001', true, 0),

-- T-02: Guide Utilisateur
('e0000000-0000-0000-0000-000000000002', 'Guide utilisateur', 'Documentation applicative destinee aux utilisateurs finaux',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"[Nom de l''application] — Guide utilisateur"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Presentation"}]},{"type":"paragraph","content":[{"type":"text","text":"[A quoi sert cette application, qui l''utilise]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Acces"}]},{"type":"paragraph","content":[{"type":"text","text":"[URL, identifiants, prerequis de connexion]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Fonctionnalites principales"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"[Fonctionnalite 1]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Description + captures d''ecran]"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"[Fonctionnalite 2]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Description + captures d''ecran]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Questions frequentes"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Question 1] → [Reponse]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Question 2] → [Reponse]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"En cas de probleme"}]},{"type":"paragraph","content":[{"type":"text","text":"[Lien vers le support / ouverture de ticket]"}]}]}',
't0000000-0000-0000-0000-000000000002', true, 0),

-- T-03: Architecture Systeme
('e0000000-0000-0000-0000-000000000003', 'Architecture systeme', 'Description technique d''un composant d''infrastructure',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"[Nom du systeme / serveur / service]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Vue d''ensemble"}]},{"type":"paragraph","content":[{"type":"text","text":"[Role, criticite, environnement (prod/preprod/dev)]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Caracteristiques techniques"}]},{"type":"paragraph","content":[{"type":"text","text":"[Hostname, OS, RAM/CPU, Stockage, Reseau]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Dependances"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Heberge : [applications]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Depend de : [services amont]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Utilise par : [equipes / services]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Acces & habilitations"}]},{"type":"paragraph","content":[{"type":"text","text":"[Qui a acces, comment, avec quels droits]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Procedures liees"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Lien vers procedure de redemarrage]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Lien vers procedure de backup]"}]}]}]}]}',
't0000000-0000-0000-0000-000000000003', true, 0),

-- T-04: FAQ
('e0000000-0000-0000-0000-000000000004', 'FAQ', 'Reponses aux questions les plus frequentes sur un sujet',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"FAQ — [Sujet]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"[Question 1 ?]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Reponse concise]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"[Question 2 ?]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Reponse concise]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"[Question 3 ?]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Reponse concise]"}]},{"type":"horizontalRule"},{"type":"paragraph","content":[{"type":"text","text":"Vous ne trouvez pas la reponse ? [Ouvrir un ticket support]"}]}]}',
't0000000-0000-0000-0000-000000000004', true, 0),

-- T-05: Troubleshooting
('e0000000-0000-0000-0000-000000000005', 'Resolution d''incident / Troubleshooting', 'Guide de diagnostic et resolution pour un probleme recurrent',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Troubleshooting — [Nom du probleme]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Symptomes"}]},{"type":"paragraph","content":[{"type":"text","text":"[Ce que l''utilisateur observe — messages d''erreur, comportement anormal]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Diagnostic"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Etape 1 : Verifier [...]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Commande ou action de verification]"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Etape 2 : Verifier [...]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Commande ou action de verification]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Solutions"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Si [condition A]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Action corrective]"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Si [condition B]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Action corrective]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Escalade"}]},{"type":"paragraph","content":[{"type":"text","text":"[Si non resolu — qui contacter, quel ticket ouvrir]"}]}]}',
't0000000-0000-0000-0000-000000000005', true, 0),

-- T-06: Fiche Applicative
('e0000000-0000-0000-0000-000000000006', 'Fiche applicative', 'Carte d''identite d''une application metier',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"[Nom de l''application]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Informations generales"}]},{"type":"paragraph","content":[{"type":"text","text":"Editeur: [...] | Version: [...] | Environnement: [Prod / Preprod] | URL: [...] | Responsable DSI: [...]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Description fonctionnelle"}]},{"type":"paragraph","content":[{"type":"text","text":"[A quoi sert l''application, qui l''utilise, quel processus metier]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Architecture technique"}]},{"type":"paragraph","content":[{"type":"text","text":"[Serveur(s), base de donnees, flux reseau]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Procedures liees"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Installation]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Mise a jour]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Sauvegarde / Restauration]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Contacts"}]},{"type":"paragraph","content":[{"type":"text","text":"[Editeur, support N2, referent interne]"}]}]}',
't0000000-0000-0000-0000-000000000006', true, 0),

-- T-07: Procedure d'Installation
('e0000000-0000-0000-0000-000000000007', 'Procedure d''installation', 'Guide d''installation d''un logiciel ou service',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Installation — [Nom du logiciel/service]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Prerequis"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[OS compatible]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Espace disque requis]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Dependances a installer]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Telechargement"}]},{"type":"paragraph","content":[{"type":"text","text":"[URL ou chemin reseau du package d''installation]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Etapes d''installation"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"1. [Etape]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Commandes ou actions]"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"2. [Etape]"}]},{"type":"paragraph","content":[{"type":"text","text":"[Commandes ou actions]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Configuration post-installation"}]},{"type":"paragraph","content":[{"type":"text","text":"[Parametres a ajuster, fichiers de config]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Verification"}]},{"type":"paragraph","content":[{"type":"text","text":"[Comment confirmer que l''installation est fonctionnelle]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Desinstallation"}]},{"type":"paragraph","content":[{"type":"text","text":"[Procedure de retour arriere si necessaire]"}]}]}',
't0000000-0000-0000-0000-000000000007', true, 0),

-- T-08: Note de Version
('e0000000-0000-0000-0000-000000000008', 'Note de version / Changelog', 'Historique des evolutions d''une application ou d''un service',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Notes de version — [Nom de l''application]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Version X.Y.Z — [Date]"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Nouveautes"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Fonctionnalite ajoutee]"}]}]}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Corrections"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Bug corrige]"}]}]}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Changements techniques"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"[Migration, mise a jour de dependance]"}]}]}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"Impact utilisateur"}]},{"type":"paragraph","content":[{"type":"text","text":"[Ce que les utilisateurs doivent savoir / faire]"}]},{"type":"horizontalRule"},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Version X.Y.Z-1 — [Date precedente]"}]},{"type":"paragraph","content":[{"type":"text","text":"[...]"}]}]}',
't0000000-0000-0000-0000-000000000008', true, 0),

-- T-09: Guide Depannage Reseau
('e0000000-0000-0000-0000-000000000009', 'Guide de depannage reseau', 'Procedure de diagnostic pour les problemes reseau recurrents',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"Depannage reseau — [Type de probleme]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Contexte"}]},{"type":"paragraph","content":[{"type":"text","text":"[Quel segment reseau, quel service impacte]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Diagnostic rapide"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"1. Verifier la connectivite"}]},{"type":"codeBlock","attrs":{"language":"bash"},"content":[{"type":"text","text":"ping -c 4 [adresse]"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"2. Verifier la resolution DNS"}]},{"type":"codeBlock","attrs":{"language":"bash"},"content":[{"type":"text","text":"nslookup [nom_hote]"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"3. Verifier les ports"}]},{"type":"codeBlock","attrs":{"language":"bash"},"content":[{"type":"text","text":"telnet [adresse] [port]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Causes frequentes"}]},{"type":"paragraph","content":[{"type":"text","text":"Timeout → Firewall → Verifier regle X | DNS fail → Serveur DNS → Relancer service"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Escalade"}]},{"type":"paragraph","content":[{"type":"text","text":"[Si non resolu → equipe Infra, ticket P2]"}]}]}',
't0000000-0000-0000-0000-000000000009', true, 0),

-- T-10: Documentation API
('e0000000-0000-0000-0000-000000000010', 'Documentation API / Service', 'Description technique d''un endpoint ou service interne',
'{"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"API / Service — [Nom]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Description"}]},{"type":"paragraph","content":[{"type":"text","text":"[Ce que fait le service, dans quel contexte il est appele]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Endpoints"}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"GET /[endpoint]"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Description : [...]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Parametres : [...]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Reponse : [...]"}]}]}]},{"type":"heading","attrs":{"level":3},"content":[{"type":"text","text":"POST /[endpoint]"}]},{"type":"bulletList","content":[{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Description : [...]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Body : [...]"}]}]},{"type":"listItem","content":[{"type":"paragraph","content":[{"type":"text","text":"Reponse : [...]"}]}]}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Authentification"}]},{"type":"paragraph","content":[{"type":"text","text":"[Token, API Key, certificat]"}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Exemples"}]},{"type":"codeBlock","attrs":{"language":"bash"},"content":[{"type":"text","text":"curl -X GET https://[...] -H \"Authorization: Bearer [...]\""}]},{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Erreurs courantes"}]},{"type":"paragraph","content":[{"type":"text","text":"401 Non autorise → Verifier le token | 500 Erreur serveur → Consulter les logs"}]}]}',
't0000000-0000-0000-0000-000000000010', true, 0)
ON CONFLICT (id) DO NOTHING;

-- 1 Admin user (password: Admin123! hashed with bcrypt cost 12)
INSERT INTO users (id, username, display_name, password_hash, role, onboarding_completed) VALUES
    ('a0000000-0000-0000-0000-000000000001', 'admin', 'Administrateur', '$2a$12$LJ3m4ys3LOwxEaFhMDjJFuYYMYhLOjKdOSCRoABbwvkZEBGQS6A4a', 'admin', false)
ON CONFLICT (id) DO NOTHING;

-- Default config
INSERT INTO config (key, value) VALUES
    ('freshness_green', '90'),
    ('freshness_yellow', '180'),
    ('ticket_url', '')
ON CONFLICT (key) DO NOTHING;

INSERT INTO schema_migrations (version) VALUES (2)
ON CONFLICT (version) DO NOTHING;

COMMIT;
